name: CI
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - name: Dotnet Publish
        run: dotnet publish --configuration Release -o ${{ github.workspace }}/demo 

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: artifact
          path: ${{ github.workspace }}//demo
          
  deploy-dev:
     name: Deploy Dev
     runs-on: ubuntu-latest
     env:
      NOME_WEBAPP_AZURE: democdactions
     environment:
       name: dev 
     needs: build
     steps:
       - uses: actions/download-artifact@v2
         with:
           name: artifact
           path: ${{ github.workspace }}//demo
           
       - name: 'Run Azure webapp deploy action using publish profile credentials'
         run: echo "passando DEV.."
     

  deploy-qa:
     name: Deploy QA
     runs-on: ubuntu-latest
     env:
      NOME_WEBAPP_AZURE: democdactions
     environment:
       name: qa 
     needs: deploy-dev
     steps:
       - uses: actions/download-artifact@v2
         with:
           name: artifact
           path: ${{ github.workspace }}//demo
           
       - name: 'Run Azure webapp deploy action using publish profile credentials'
         run: echo "passando QA.."
         
  deploy-prd:
     name: Deploy Produção
     runs-on: ubuntu-latest
     env:
      NOME_WEBAPP_AZURE: democdactions
     environment:
       name: prd 
     needs: deploy-qa
     steps:
       - uses: actions/download-artifact@v2
         with:
           name: artifact
           path: ${{ github.workspace }}//demo
           
       - name: 'Run Azure webapp deploy action using publish profile credentials'
         run: echo "passando PROD.."
